name: CI Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - issue*
      - v4.*

jobs:
  staticanalyses:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout carddavclient
        uses: actions/checkout@v2
      - name: Set up CI environment
        uses: ./.github/actions/setup
        with:
          php-version: '8.0'
      - name: Check code style compliance with PSR12
        run: make stylecheck
      - name: Check code compatibility with minimum supported PHP version
        run: make phpcompatcheck
      - name: Run psalm static analysis
        run: make psalmanalysis

  unittests:
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.3', '7.4', '8.0', '8.1']

    runs-on: ubuntu-20.04

    env:
      XDEBUG_MODE: coverage

    steps:
      - name: Checkout carddavclient
        uses: actions/checkout@v2
      - name: Set up CI environment
        uses: ./.github/actions/setup
        with:
          php-version: '8.0'
      - name: Run unit tests
        run: make unittests
      - name: Upload unit test coverage reports to codecov.io
        uses: codecov/codecov-action@v1
        with:
          file: testreports/unit/clover.xml
          flags: unittests
          name: Carddavclient unit test coverage
          fail_ci_if_error: false

  interop-nextcloud:
    strategy:
      fail-fast: false
      matrix:
        nextcloud-version: ['21', '22', '23']

    runs-on: ubuntu-20.04

    env:
      XDEBUG_MODE: coverage

    services:
      nextcloud:
        image: nextcloud:${{ matrix.nextcloud-version }}
        options: >-
          --name nextcloud
        ports:
          - 8080:80

    steps:
      - name: Checkout carddavclient
        uses: actions/checkout@v2
      - name: Set up CI environment
        uses: ./.github/actions/setup
        with:
          php-version: '8.0'
      - name: Setup Nextcloud
        run: |
          sudo docker exec --user www-data nextcloud php occ maintenance:install --admin-user=ncadm --admin-pass=ncadmPassw0rd
          sudo docker exec --user www-data nextcloud php occ app:install contacts
          sudo docker exec --user www-data nextcloud php occ app:disable contactsinteraction
      - name: Run interop tests
        run: make tests-interop
      - name: Upload interop-nextcloud test coverage reports to codecov.io
        uses: codecov/codecov-action@v1
        with:
          file: testreports/interop/clover.xml
          flags: interop
          name: Carddavclient nextcloud interoperability test coverage
          fail_ci_if_error: false
